{"uuid": "0a75abbd-c4b8-4493-96cd-c85c165efa47", "children": ["f2da6e24-129f-4a4e-9d85-185aa740e9f1"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "TypeError: api_code() got an unexpected keyword argument 'json'\n", "trace": "  File \"D:\\anaconda\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ApiTest\\test_case\\conftest.py\", line 30, in login_fixture\n    loginApi.send_code(data)\n  File \"D:\\ApiTest\\api\\login_ok.py\", line 24, in send_code\n    response = api_util.api_code(json=json_data).json()\n"}, "start": 1723729038013, "stop": 1723729038039}], "start": 1723729038013, "stop": 1723729038328}