{"uuid": "6d80deac-86cb-4dc2-9589-e25bc20cfe62", "children": ["2d55ad59-f267-4ce7-bd58-ea340162c83c"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\ApiTest\\\\data\\\\data.yaml'\n", "trace": "  File \"D:\\anaconda\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ApiTest\\test_case\\conftest.py\", line 25, in login_fixture\n    data = get_data()['user_login']\n  File \"D:\\ApiTest\\test_case\\conftest.py\", line 7, in get_data\n    return base_data.read_data()\n  File \"D:\\ApiTest\\utils\\read.py\", line 24, in read_data\n    f = open(self.data_path, encoding=\"utf8\")\n"}, "start": 1723711007543, "stop": 1723711007543}], "start": 1723711007543, "stop": 1723711007675}