{"uuid": "6acca294-4358-4b9c-b500-9cbfc36c6347", "children": ["be197307-37e2-4027-84f8-65fcf4517bea"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../config/data.yaml'\n", "trace": "  File \"D:\\anaconda\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ApiTest\\test_case\\conftest.py\", line 26, in login_fixture\n    data = get_data()['login1']\n  File \"D:\\ApiTest\\test_case\\conftest.py\", line 8, in get_data\n    return base_data.read_data()\n  File \"D:\\ApiTest\\utils\\read.py\", line 23, in read_data\n    f = open(self.data_path, encoding=\"utf8\")\n"}, "start": 1723717267629, "stop": 1723717267629}], "start": 1723717267629, "stop": 1723717267782}