{"uuid": "a4ef5359-a68e-4f20-bb49-d905e14f64da", "children": ["b592c142-c872-4415-b27e-c3230e89e00e"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "TypeError: api_code() got an unexpected keyword argument 'json'\n", "trace": "  File \"D:\\anaconda\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ApiTest\\test_case\\conftest.py\", line 30, in login_fixture\n    loginApi.send_code(data)\n  File \"D:\\ApiTest\\api\\login_ok.py\", line 24, in send_code\n    response = api_util.api_code(json=json_data).json()\n"}, "start": 1723729112725, "stop": 1723729112739}], "start": 1723729112725, "stop": 1723729112988}