{"uuid": "d9fa8b5b-6f4e-4a7d-89b5-cb618969aa05", "children": ["f44cf8f6-5985-4eae-a240-19196cb50d3f"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginApi' object has no attribute 'uuid'\n", "trace": "  File \"D:\\anaconda\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\anaconda\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ApiTest\\test_case\\conftest.py\", line 30, in login_fixture\n    result= loginApi.login(username,password,code)\n  File \"D:\\ApiTest\\api\\login_ok.py\", line 42, in login\n    \"uuid\":self.uuid\n"}, "start": 1723727850728, "stop": 1723727850754}], "start": 1723727850728, "stop": 1723727851071}